site_name: Documentaci√≥n de prueba para PIG
site_url: https://github.com/victor-MMN/PIG-doc-test
theme:
    name: material

    palette:
      - scheme: default
        toggle:
          icon: material/weather-sunny
          name: Light mode
        primary: teal
        accent: light green

      - scheme: slate
        toggle:
          icon: material/weather-night
          name: Night mode
        primary: teal
        accent: light green

    font:
      text: Merriweather Sans
      code: JetBrains Mono

    features:
      - navigation.indexes

nav:
  - Acceso al cluster de PIG:
    - cluster_access/01_linux.md
    - cluster_access/02_windows.md
    - cluster_access/03_my_fist_pod.md
markdown_extensions:
   - admonition
   - pymdownx.details
   - pymdownx.superfences
   - footnotes
   - attr_list
   - md_in_html